name: Black Formatter

on: [push]

jobs:
  apply-black:
    if: contains(github.event.commits.*.message,'GitHub Actions - Formatted using black formatter.') == false
    name: Apply Black Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        fetch-depth: 0 
    - name: Run Black
      uses: lgeiger/black-action@master
      with:
        args: .
    - name: Git config
      run: |
        git config --local remote.origin.url "https://${{ github.token }}@github.com/${{ github.repository }}.git"
    - name: Commit files
      run: git commit -S -am 'GitHub Actions - Formatted using black formatter.'
    - name: Push changes
      run: git push origin main
